### ISSUE TITLE
Feature request: Import theme from fzf commands

### ISSUE THREAD

**Issue by haunt98** [vitormv/fzf-themes#1]
Hi @vitormv, thanks for great project! Now I can custom fzf themes more easily.

But I have a small request, can you add import themes from fzf commands?

For example I use [catppuccin/fzf](https://github.com/catppuccin/fzf):

```sh
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
```

**Comment by vitormv** [comment]
Hi, actually I had thought of adding that from the beginning, but it got kind of pushed to the future. Parsing very simple command line options is straightforward, but things might go very wrong if people paste more complex strings, specially with other variables, and weird quoting and so on. So it requires very throughout testing.

I still want to make it though, ill try to find some npm library that can help with parsing command line strings

**Comment by haunt98** [comment]
Thanks @vitormv  for now it is also too good for me to rice my unixbox.

**Comment by vitormv** [comment]
@haunt98 it's there, you can now import themes from FZF_DEFAULT_OPTS args :)

**Comment by haunt98** [comment]
Thanks @vitormv 

My config:

```zsh
    export FZF_DEFAULT_OPTS="\
        --ansi \
        --pointer='🔫' --prompt='🪓 ' \
        --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
        --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
        --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
```

Your preview is outstanding!

<img width="961" alt="image" src="https://github.com/vitormv/fzf-themes/assets/5424272/0e71d341-b63a-408c-9f8d-9e64d4e9aab9">
